version: '3' 

services:
    dropbox:
      image: hillliu/dropbox-slim
      volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /tmp:/tmp
      - ./:/data
      user: "${MY_USER-65534:65534}"
