version: "3"

services:
  dropbox:
    image: hillliu/dropbox-slim
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /tmp:/tmp
      - ./:/data
    environment:
      - DROPBOXUSER=${DROPBOXUSER:-#65534}
